# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Featured',   url: 'Featured'}
- {name: 'Posts',      url: 'all-posts'}
- {name: 'Movies',      url: 'Movies'}
- {name: 'Interviews', url: 'Interviews'}
# - {name: 'About',      url: 'https://cs.colby.edu/nsalmadi/'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/NaserAlMadi1'}
- {icon: 'linkedin', link:   'https://www.linkedin.com/in/nasermadi/'}
- {icon: 'youtube', link:   'https://www.youtube.com/@prof_naser'}


# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
